// <auto-generated />
using System;
using System.Collections.Generic;
using BarBrain.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace BarBrain.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706220913_Sprint1Catalog")]
    partial class Sprint1Catalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarBrain.Api.Data.Entities.AttributeDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<short?>("BridgeIndex")
                        .HasColumnType("smallint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<short>("DimIndex")
                        .HasColumnType("smallint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Key");

                    b.HasIndex("Category", "BridgeIndex")
                        .IsUnique()
                        .HasFilter("\"BridgeIndex\" IS NOT NULL");

                    b.HasIndex("Category", "DimIndex")
                        .IsUnique();

                    b.ToTable("attribute_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_attribute_definitions_bridge_index", "\"BridgeIndex\" IS NULL OR (\"BridgeIndex\" >= 0 AND \"BridgeIndex\" < 6)");

                            t.HasCheckConstraint("ck_attribute_definitions_category", "\"Category\" IN ('beer','whiskey','wine')");

                            t.HasCheckConstraint("ck_attribute_definitions_dim_index", "\"DimIndex\" >= 0 AND \"DimIndex\" < 8");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Drink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Abv")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<Vector>("BridgeVector")
                        .HasColumnType("vector(6)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Vector>("CategoryVector")
                        .HasColumnType("vector(8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MergedIntoDrinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("StyleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("BridgeVector")
                        .HasDatabaseName("ix_drinks_bridge_vector_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BridgeVector"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("BridgeVector"), new[] { "vector_cosine_ops" });

                    b.HasIndex("CategoryVector")
                        .HasDatabaseName("ix_drinks_category_vector_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CategoryVector"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("CategoryVector"), new[] { "vector_cosine_ops" });

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_drinks_normalized_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Category", "StyleId");

                    b.HasIndex("MergedIntoDrinkId", "Category");

                    b.HasIndex("Source", "SourceRef")
                        .IsUnique()
                        .HasFilter("\"SourceRef\" IS NOT NULL");

                    b.HasIndex("StyleId", "Category");

                    b.HasIndex("ProducerId", "Category", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_drinks_canonical_identity")
                        .HasFilter("\"Status\" = 'active'");

                    b.ToTable("drinks", null, t =>
                        {
                            t.HasCheckConstraint("ck_drinks_abv", "\"Abv\" IS NULL OR (\"Abv\" >= 0 AND \"Abv\" <= 100)");

                            t.HasCheckConstraint("ck_drinks_category", "\"Category\" IN ('beer','whiskey','wine')");

                            t.HasCheckConstraint("ck_drinks_merge_pairing", "(\"Status\" = 'merged') = (\"MergedIntoDrinkId\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_drinks_no_self_merge", "\"MergedIntoDrinkId\" IS NULL OR \"MergedIntoDrinkId\" <> \"Id\"");

                            t.HasCheckConstraint("ck_drinks_owner_visibility", "\"CreatedByUserId\" IS NOT NULL OR \"Visibility\" = 'public'");

                            t.HasCheckConstraint("ck_drinks_status", "\"Status\" IN ('active','merged')");

                            t.HasCheckConstraint("ck_drinks_visibility", "\"Visibility\" IN ('public','private')");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.DrinkAttributeValue", b =>
                {
                    b.Property<Guid>("DrinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("DrinkId", "AttributeKey");

                    b.HasIndex("AttributeKey");

                    b.ToTable("drink_attributes", null, t =>
                        {
                            t.HasCheckConstraint("ck_drink_attributes_confidence", "\"Confidence\" >= 0 AND \"Confidence\" <= 1");

                            t.HasCheckConstraint("ck_drink_attributes_source", "\"Source\" IN ('inherited','manufacturer','crowd','llm','moderator')");

                            t.HasCheckConstraint("ck_drink_attributes_value", "\"Value\" >= 0 AND \"Value\" <= 1");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.EventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("Properties")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OccurredAt");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.MergeCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<float>("Similarity")
                        .HasColumnType("real");

                    b.Property<Guid?>("SourceDrinkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceProducerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TargetDrinkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetProducerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceDrinkId");

                    b.HasIndex("SourceProducerId");

                    b.HasIndex("TargetDrinkId");

                    b.HasIndex("TargetProducerId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("EntityType", "SourceProducerId", "TargetProducerId", "SourceDrinkId", "TargetDrinkId")
                        .IsUnique()
                        .HasDatabaseName("ux_merge_queue_pending_pair")
                        .HasFilter("\"Status\" = 'pending'");

                    b.ToTable("merge_queue", null, t =>
                        {
                            t.HasCheckConstraint("ck_merge_queue_decision", "(\"Status\" = 'pending') = (\"DecidedAt\" IS NULL)");

                            t.HasCheckConstraint("ck_merge_queue_distinct_pair", "(\"SourceProducerId\" IS NULL OR \"SourceProducerId\" <> \"TargetProducerId\") AND (\"SourceDrinkId\" IS NULL OR \"SourceDrinkId\" <> \"TargetDrinkId\")");

                            t.HasCheckConstraint("ck_merge_queue_entity_type", "\"EntityType\" IN ('producer','drink')");

                            t.HasCheckConstraint("ck_merge_queue_similarity", "\"Similarity\" >= 0 AND \"Similarity\" <= 1");

                            t.HasCheckConstraint("ck_merge_queue_status", "\"Status\" IN ('pending','approved','rejected')");

                            t.HasCheckConstraint("ck_merge_queue_typed_pair", "(\"EntityType\" = 'producer' AND \"SourceProducerId\" IS NOT NULL AND \"TargetProducerId\" IS NOT NULL AND \"SourceDrinkId\" IS NULL AND \"TargetDrinkId\" IS NULL) OR (\"EntityType\" = 'drink' AND \"SourceDrinkId\" IS NOT NULL AND \"TargetDrinkId\" IS NOT NULL AND \"SourceProducerId\" IS NULL AND \"TargetProducerId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Producer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Country")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MergedIntoProducerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProducerType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MergedIntoProducerId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_producers_normalized_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Source", "SourceRef")
                        .IsUnique()
                        .HasFilter("\"SourceRef\" IS NOT NULL");

                    b.ToTable("producers", null, t =>
                        {
                            t.HasCheckConstraint("ck_producers_merge_pairing", "(\"Status\" = 'merged') = (\"MergedIntoProducerId\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_producers_no_self_merge", "\"MergedIntoProducerId\" IS NULL OR \"MergedIntoProducerId\" <> \"Id\"");

                            t.HasCheckConstraint("ck_producers_owner_visibility", "\"CreatedByUserId\" IS NOT NULL OR \"Visibility\" = 'public'");

                            t.HasCheckConstraint("ck_producers_status", "\"Status\" IN ('active','merged')");

                            t.HasCheckConstraint("ck_producers_type", "\"ProducerType\" IS NULL OR \"ProducerType\" IN ('brewery','distillery','winery','cidery','meadery','multi','other')");

                            t.HasCheckConstraint("ck_producers_visibility", "\"Visibility\" IN ('public','private')");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Style", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AbvMax")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<decimal?>("AbvMin")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<Vector>("BridgeVector")
                        .HasColumnType("vector(6)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Vector>("CategoryVector")
                        .HasColumnType("vector(8)");

                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FgMax")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<decimal?>("FgMin")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<short?>("IbuMax")
                        .HasColumnType("smallint");

                    b.Property<short?>("IbuMin")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("OgMax")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<decimal?>("OgMin")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<Guid?>("ParentStyleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("SrmMax")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<decimal?>("SrmMin")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentStyleId");

                    b.HasIndex("Category", "Code")
                        .IsUnique()
                        .HasFilter("\"Code\" IS NOT NULL");

                    b.HasIndex("Category", "NormalizedName");

                    b.ToTable("styles", null, t =>
                        {
                            t.HasCheckConstraint("ck_styles_abv_range", "(\"AbvMin\" IS NULL OR \"AbvMin\" >= 0) AND (\"AbvMin\" IS NULL OR \"AbvMax\" IS NULL OR \"AbvMin\" <= \"AbvMax\")");

                            t.HasCheckConstraint("ck_styles_category", "\"Category\" IN ('beer','whiskey','wine')");

                            t.HasCheckConstraint("ck_styles_fg_range", "(\"FgMin\" IS NULL OR \"FgMax\" IS NULL OR \"FgMin\" <= \"FgMax\")");

                            t.HasCheckConstraint("ck_styles_ibu_range", "(\"IbuMin\" IS NULL OR \"IbuMin\" >= 0) AND (\"IbuMin\" IS NULL OR \"IbuMax\" IS NULL OR \"IbuMin\" <= \"IbuMax\")");

                            t.HasCheckConstraint("ck_styles_og_range", "(\"OgMin\" IS NULL OR \"OgMax\" IS NULL OR \"OgMin\" <= \"OgMax\")");

                            t.HasCheckConstraint("ck_styles_srm_range", "(\"SrmMin\" IS NULL OR \"SrmMin\" >= 0) AND (\"SrmMin\" IS NULL OR \"SrmMax\" IS NULL OR \"SrmMin\" <= \"SrmMax\")");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.StyleAttributeValue", b =>
                {
                    b.Property<Guid>("StyleId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("StyleId", "AttributeKey");

                    b.HasIndex("AttributeKey");

                    b.ToTable("style_attributes", null, t =>
                        {
                            t.HasCheckConstraint("ck_style_attributes_value", "\"Value\" >= 0 AND \"Value\" <= 1");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Handle")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Handle")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Drink", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarBrain.Api.Data.Entities.Producer", "Producer")
                        .WithMany("Drinks")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "MergedInto")
                        .WithMany()
                        .HasForeignKey("MergedIntoDrinkId", "Category")
                        .HasPrincipalKey("Id", "Category")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarBrain.Api.Data.Entities.Style", "Style")
                        .WithMany("Drinks")
                        .HasForeignKey("StyleId", "Category")
                        .HasPrincipalKey("Id", "Category")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("MergedInto");

                    b.Navigation("Producer");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.DrinkAttributeValue", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "Drink")
                        .WithMany("Attributes")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.MergeCandidate", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "SourceDrink")
                        .WithMany()
                        .HasForeignKey("SourceDrinkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarBrain.Api.Data.Entities.Producer", "SourceProducer")
                        .WithMany()
                        .HasForeignKey("SourceProducerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "TargetDrink")
                        .WithMany()
                        .HasForeignKey("TargetDrinkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarBrain.Api.Data.Entities.Producer", "TargetProducer")
                        .WithMany()
                        .HasForeignKey("TargetProducerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SourceDrink");

                    b.Navigation("SourceProducer");

                    b.Navigation("TargetDrink");

                    b.Navigation("TargetProducer");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Producer", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarBrain.Api.Data.Entities.Producer", "MergedInto")
                        .WithMany()
                        .HasForeignKey("MergedIntoProducerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("MergedInto");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Style", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.Style", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentStyleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.StyleAttributeValue", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Style", "Style")
                        .WithMany("Attributes")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Drink", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Producer", b =>
                {
                    b.Navigation("Drinks");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Style", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Children");

                    b.Navigation("Drinks");
                });
#pragma warning restore 612, 618
        }
    }
}
