// <auto-generated />
using System;
using System.Collections.Generic;
using BarBrain.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace BarBrain.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711232053_Sprint7Privacy")]
    partial class Sprint7Privacy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarBrain.Api.Data.Entities.AnomalyFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Score");

                    b.HasIndex("UserId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_anomaly_flags_open_per_user_kind")
                        .HasFilter("\"Status\" = 'open'");

                    b.ToTable("anomaly_flags", null, t =>
                        {
                            t.HasCheckConstraint("ck_anomaly_flags_decision", "(\"Status\" = 'open') = (\"DecidedAt\" IS NULL)");

                            t.HasCheckConstraint("ck_anomaly_flags_kind", "\"Kind\" IN ('rating_zscore_outlier','rapid_fire')");

                            t.HasCheckConstraint("ck_anomaly_flags_status", "\"Status\" IN ('open','cleared','actioned')");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.AttributeDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<short?>("BridgeIndex")
                        .HasColumnType("smallint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<short>("DimIndex")
                        .HasColumnType("smallint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Key");

                    b.HasIndex("Category", "BridgeIndex")
                        .IsUnique()
                        .HasFilter("\"BridgeIndex\" IS NOT NULL");

                    b.HasIndex("Category", "DimIndex")
                        .IsUnique();

                    b.ToTable("attribute_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_attribute_definitions_bridge_index", "\"BridgeIndex\" IS NULL OR (\"BridgeIndex\" >= 0 AND \"BridgeIndex\" < 6)");

                            t.HasCheckConstraint("ck_attribute_definitions_category", "\"Category\" IN ('beer','whiskey','wine')");

                            t.HasCheckConstraint("ck_attribute_definitions_dim_index", "\"DimIndex\" >= 0 AND \"DimIndex\" < 8");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.BadgeDefinition", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisplayGroup")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Slug");

                    b.ToTable("badge_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_badge_definitions_group", "\"DisplayGroup\" IN ('breadth','exploration','venues','contribution','streak')");

                            t.HasCheckConstraint("ck_badge_definitions_metric", "\"Metric\" IN ('distinct_styles_rated','distinct_categories_rated','wildcard_distinct_drinks','distinct_venues_checked_in','wiki_contributions','menu_confirms','accepted_merge_contributions','weekly_streak_weeks')");

                            t.HasCheckConstraint("ck_badge_definitions_threshold", "\"Threshold\" >= 1");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Checkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_checkins_one_open_per_user")
                        .HasFilter("\"EndedAt\" IS NULL");

                    b.HasIndex("VenueId", "CreatedAt")
                        .HasDatabaseName("ix_checkins_venue_recent");

                    b.ToTable("checkins", null, t =>
                        {
                            t.HasCheckConstraint("ck_checkins_ended", "\"EndedAt\" IS NULL OR \"EndedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("ck_checkins_window", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Drink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Abv")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<Vector>("BridgeVector")
                        .HasColumnType("vector(6)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Vector>("CategoryVector")
                        .HasColumnType("vector(8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HiddenBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("MergedIntoDrinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("StyleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("BridgeVector")
                        .HasDatabaseName("ix_drinks_bridge_vector_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BridgeVector"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("BridgeVector"), new[] { "vector_cosine_ops" });

                    b.HasIndex("CategoryVector")
                        .HasDatabaseName("ix_drinks_category_vector_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CategoryVector"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("CategoryVector"), new[] { "vector_cosine_ops" });

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_drinks_normalized_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Category", "StyleId");

                    b.HasIndex("MergedIntoDrinkId", "Category");

                    b.HasIndex("Source", "SourceRef")
                        .IsUnique()
                        .HasFilter("\"SourceRef\" IS NOT NULL");

                    b.HasIndex("StyleId", "Category");

                    b.HasIndex("ProducerId", "Category", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_drinks_canonical_identity")
                        .HasFilter("\"Status\" = 'active'");

                    b.ToTable("drinks", null, t =>
                        {
                            t.HasCheckConstraint("ck_drinks_abv", "\"Abv\" IS NULL OR (\"Abv\" >= 0 AND \"Abv\" <= 100)");

                            t.HasCheckConstraint("ck_drinks_category", "\"Category\" IN ('beer','whiskey','wine')");

                            t.HasCheckConstraint("ck_drinks_hidden_pairing", "(\"HiddenAt\" IS NULL) = (\"HiddenBy\" IS NULL)");

                            t.HasCheckConstraint("ck_drinks_merge_pairing", "(\"Status\" = 'merged') = (\"MergedIntoDrinkId\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_drinks_no_self_merge", "\"MergedIntoDrinkId\" IS NULL OR \"MergedIntoDrinkId\" <> \"Id\"");

                            t.HasCheckConstraint("ck_drinks_owner_visibility", "\"CreatedByUserId\" IS NOT NULL OR \"Visibility\" = 'public'");

                            t.HasCheckConstraint("ck_drinks_status", "\"Status\" IN ('active','merged')");

                            t.HasCheckConstraint("ck_drinks_visibility", "\"Visibility\" IN ('public','private')");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.DrinkAttributeValue", b =>
                {
                    b.Property<Guid>("DrinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("DrinkId", "AttributeKey");

                    b.HasIndex("AttributeKey");

                    b.ToTable("drink_attributes", null, t =>
                        {
                            t.HasCheckConstraint("ck_drink_attributes_confidence", "\"Confidence\" >= 0 AND \"Confidence\" <= 1");

                            t.HasCheckConstraint("ck_drink_attributes_source", "\"Source\" IN ('inherited','manufacturer','crowd','llm','moderator')");

                            t.HasCheckConstraint("ck_drink_attributes_value", "\"Value\" >= 0 AND \"Value\" <= 1");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.EventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("Properties")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OccurredAt");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.MergeCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<float>("Similarity")
                        .HasColumnType("real");

                    b.Property<Guid?>("SourceDrinkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceProducerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceVenueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TargetDrinkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetProducerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetVenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceDrinkId");

                    b.HasIndex("SourceProducerId");

                    b.HasIndex("SourceVenueId");

                    b.HasIndex("TargetDrinkId");

                    b.HasIndex("TargetProducerId");

                    b.HasIndex("TargetVenueId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("EntityType", "SourceProducerId", "TargetProducerId", "SourceDrinkId", "TargetDrinkId", "SourceVenueId", "TargetVenueId")
                        .IsUnique()
                        .HasDatabaseName("ux_merge_queue_pending_pair")
                        .HasFilter("\"Status\" = 'pending'");

                    b.ToTable("merge_queue", null, t =>
                        {
                            t.HasCheckConstraint("ck_merge_queue_decision", "(\"Status\" = 'pending') = (\"DecidedAt\" IS NULL)");

                            t.HasCheckConstraint("ck_merge_queue_distinct_pair", "(\"SourceProducerId\" IS NULL OR \"SourceProducerId\" <> \"TargetProducerId\") AND (\"SourceDrinkId\" IS NULL OR \"SourceDrinkId\" <> \"TargetDrinkId\") AND (\"SourceVenueId\" IS NULL OR \"SourceVenueId\" <> \"TargetVenueId\")");

                            t.HasCheckConstraint("ck_merge_queue_entity_type", "\"EntityType\" IN ('producer','drink','venue')");

                            t.HasCheckConstraint("ck_merge_queue_similarity", "\"Similarity\" >= 0 AND \"Similarity\" <= 1");

                            t.HasCheckConstraint("ck_merge_queue_status", "\"Status\" IN ('pending','approved','rejected')");

                            t.HasCheckConstraint("ck_merge_queue_typed_pair", "(\"EntityType\" = 'producer' AND \"SourceProducerId\" IS NOT NULL AND \"TargetProducerId\" IS NOT NULL AND \"SourceDrinkId\" IS NULL AND \"TargetDrinkId\" IS NULL AND \"SourceVenueId\" IS NULL AND \"TargetVenueId\" IS NULL) OR (\"EntityType\" = 'drink' AND \"SourceDrinkId\" IS NOT NULL AND \"TargetDrinkId\" IS NOT NULL AND \"SourceProducerId\" IS NULL AND \"TargetProducerId\" IS NULL AND \"SourceVenueId\" IS NULL AND \"TargetVenueId\" IS NULL) OR (\"EntityType\" = 'venue' AND \"SourceVenueId\" IS NOT NULL AND \"TargetVenueId\" IS NOT NULL AND \"SourceProducerId\" IS NULL AND \"TargetProducerId\" IS NULL AND \"SourceDrinkId\" IS NULL AND \"TargetDrinkId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.ModerationAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("Details")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("moderation_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_moderation_actions_action", "\"Action\" IN ('merge_approved','merge_rejected','report_actioned','report_dismissed','content_hidden','content_unhidden','shadow_limited','shadow_cleared','banned','unbanned','anomaly_cleared')");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Producer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Country")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MergedIntoProducerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProducerType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MergedIntoProducerId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_producers_normalized_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Source", "SourceRef")
                        .IsUnique()
                        .HasFilter("\"SourceRef\" IS NOT NULL");

                    b.ToTable("producers", null, t =>
                        {
                            t.HasCheckConstraint("ck_producers_merge_pairing", "(\"Status\" = 'merged') = (\"MergedIntoProducerId\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_producers_no_self_merge", "\"MergedIntoProducerId\" IS NULL OR \"MergedIntoProducerId\" <> \"Id\"");

                            t.HasCheckConstraint("ck_producers_owner_visibility", "\"CreatedByUserId\" IS NOT NULL OR \"Visibility\" = 'public'");

                            t.HasCheckConstraint("ck_producers_status", "\"Status\" IN ('active','merged')");

                            t.HasCheckConstraint("ck_producers_type", "\"ProducerType\" IS NULL OR \"ProducerType\" IN ('brewery','distillery','winery','cidery','meadery','multi','other')");

                            t.HasCheckConstraint("ck_producers_visibility", "\"Visibility\" IN ('public','private')");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DrinkId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HiddenBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationContext")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RecSection")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex("CreatedByUserId", "CreatedAt")
                        .HasDatabaseName("ix_ratings_journal");

                    b.HasIndex("CreatedByUserId", "DrinkId")
                        .IsUnique()
                        .HasDatabaseName("ux_ratings_latest_per_user_drink")
                        .HasFilter("\"IsLatest\"");

                    b.HasIndex("DrinkId", "Visibility", "IsLatest");

                    b.ToTable("ratings", null, t =>
                        {
                            t.HasCheckConstraint("ck_ratings_hidden_pairing", "(\"HiddenAt\" IS NULL) = (\"HiddenBy\" IS NULL)");

                            t.HasCheckConstraint("ck_ratings_location_context", "\"LocationContext\" IN ('home_bar','venue','untagged')");

                            t.HasCheckConstraint("ck_ratings_origin", "\"Origin\" IN ('user','quiz')");

                            t.HasCheckConstraint("ck_ratings_rec_section", "\"RecSection\" IS NULL OR \"RecSection\" IN ('up_your_alley','stretch_a_little','wildcard','loved_by_your_matches')");

                            t.HasCheckConstraint("ck_ratings_value", "\"Value\" >= 1.0 AND \"Value\" <= 5.0 AND (\"Value\" * 2) = floor(\"Value\" * 2)");

                            t.HasCheckConstraint("ck_ratings_venue_pairing", "(\"LocationContext\" = 'untagged') = (\"VenueId\" IS NULL)");

                            t.HasCheckConstraint("ck_ratings_visibility", "\"Visibility\" IN ('public','private')");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("DrinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RatingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.HasIndex("RatingId");

                    b.HasIndex("VenueId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("ReporterUserId", "RatingId", "VenueId", "DrinkId")
                        .IsUnique()
                        .HasDatabaseName("ux_reports_open_per_reporter_target")
                        .HasFilter("\"Status\" = 'open'");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_reports_decision", "(\"Status\" = 'open') = (\"DecidedAt\" IS NULL)");

                            t.HasCheckConstraint("ck_reports_entity_type", "\"EntityType\" IN ('rating','venue','drink')");

                            t.HasCheckConstraint("ck_reports_reason", "\"Reason\" IN ('inaccurate','spam','offensive','other')");

                            t.HasCheckConstraint("ck_reports_status", "\"Status\" IN ('open','actioned','dismissed')");

                            t.HasCheckConstraint("ck_reports_typed_target", "(\"EntityType\" = 'rating' AND \"RatingId\" IS NOT NULL AND \"VenueId\" IS NULL AND \"DrinkId\" IS NULL) OR (\"EntityType\" = 'venue' AND \"VenueId\" IS NOT NULL AND \"RatingId\" IS NULL AND \"DrinkId\" IS NULL) OR (\"EntityType\" = 'drink' AND \"DrinkId\" IS NOT NULL AND \"RatingId\" IS NULL AND \"VenueId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Style", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AbvMax")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<decimal?>("AbvMin")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<Vector>("BridgeVector")
                        .HasColumnType("vector(6)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Vector>("CategoryVector")
                        .HasColumnType("vector(8)");

                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FgMax")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<decimal?>("FgMin")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<short?>("IbuMax")
                        .HasColumnType("smallint");

                    b.Property<short?>("IbuMin")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("OgMax")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<decimal?>("OgMin")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<Guid?>("ParentStyleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("SrmMax")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<decimal?>("SrmMin")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentStyleId");

                    b.HasIndex("Category", "Code")
                        .IsUnique()
                        .HasFilter("\"Code\" IS NOT NULL");

                    b.HasIndex("Category", "NormalizedName");

                    b.ToTable("styles", null, t =>
                        {
                            t.HasCheckConstraint("ck_styles_abv_range", "(\"AbvMin\" IS NULL OR \"AbvMin\" >= 0) AND (\"AbvMin\" IS NULL OR \"AbvMax\" IS NULL OR \"AbvMin\" <= \"AbvMax\")");

                            t.HasCheckConstraint("ck_styles_category", "\"Category\" IN ('beer','whiskey','wine')");

                            t.HasCheckConstraint("ck_styles_fg_range", "(\"FgMin\" IS NULL OR \"FgMax\" IS NULL OR \"FgMin\" <= \"FgMax\")");

                            t.HasCheckConstraint("ck_styles_ibu_range", "(\"IbuMin\" IS NULL OR \"IbuMin\" >= 0) AND (\"IbuMin\" IS NULL OR \"IbuMax\" IS NULL OR \"IbuMin\" <= \"IbuMax\")");

                            t.HasCheckConstraint("ck_styles_og_range", "(\"OgMin\" IS NULL OR \"OgMax\" IS NULL OR \"OgMin\" <= \"OgMax\")");

                            t.HasCheckConstraint("ck_styles_srm_range", "(\"SrmMin\" IS NULL OR \"SrmMin\" >= 0) AND (\"SrmMin\" IS NULL OR \"SrmMax\" IS NULL OR \"SrmMin\" <= \"SrmMax\")");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.StyleAttributeValue", b =>
                {
                    b.Property<Guid>("StyleId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("StyleId", "AttributeKey");

                    b.HasIndex("AttributeKey");

                    b.ToTable("style_attributes", null, t =>
                        {
                            t.HasCheckConstraint("ck_style_attributes_value", "\"Value\" >= 0 AND \"Value\" <= 1");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AttestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionMode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DigestUnsubscribeToken")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DigestUnsubscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("HandleChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HideFromMatches")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModerationNote")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ShadowLimitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Handle");

                    b.HasKey("Id");

                    b.HasIndex("DigestUnsubscribeToken")
                        .IsUnique()
                        .HasDatabaseName("ux_users_digest_unsub_token");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email")
                        .HasFilter("\"NormalizedEmail\" IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_users_Handle");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_activation_requires_gate", "\"ActivatedAt\" IS NULL OR (\"BirthYear\" IS NOT NULL AND \"AttestedAt\" IS NOT NULL AND \"Handle\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_users_birth_year", "\"BirthYear\" IS NULL OR (\"BirthYear\" >= 1900 AND \"BirthYear\" <= 2100)");

                            t.HasCheckConstraint("ck_users_deletion_mode", "\"DeletionMode\" IS NULL OR \"DeletionMode\" IN ('delete','anonymize')");

                            t.HasCheckConstraint("ck_users_deletion_pairing", "(\"DeletionRequestedAt\" IS NULL) = (\"DeletionMode\" IS NULL)");

                            t.HasCheckConstraint("ck_users_handle_lowercase", "\"Handle\" IS NULL OR \"Handle\" = lower(\"Handle\")");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BadgeSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeSlug");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_badges_unseen")
                        .HasFilter("\"SeenAt\" IS NULL");

                    b.HasIndex("UserId", "BadgeSlug")
                        .IsUnique()
                        .HasDatabaseName("ux_user_badges_user_badge");

                    b.ToTable("user_badges", (string)null);
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.UserCategoryInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Category");

                    b.ToTable("user_category_interests", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_category_interests_category", "\"Category\" IN ('beer','whiskey','wine')");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.UserMatchNeighbor", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NeighborUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("AttributeSimilarity")
                        .HasColumnType("double precision");

                    b.Property<double>("BlendedScore")
                        .HasColumnType("double precision");

                    b.Property<int>("CoRatedCount")
                        .HasColumnType("integer");

                    b.Property<double?>("CoRatingAgreement")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "NeighborUserId", "Category");

                    b.HasIndex("NeighborUserId");

                    b.HasIndex("UserId", "BlendedScore")
                        .HasDatabaseName("ix_user_match_neighbors_user_score");

                    b.ToTable("user_match_neighbors", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_match_neighbors_category", "\"Category\" IN ('beer','whiskey','wine')");

                            t.HasCheckConstraint("ck_user_match_neighbors_corated", "\"CoRatedCount\" >= 0");

                            t.HasCheckConstraint("ck_user_match_neighbors_no_self", "\"UserId\" <> \"NeighborUserId\"");

                            t.HasCheckConstraint("ck_user_match_neighbors_score", "\"BlendedScore\" >= 0 AND \"BlendedScore\" <= 1");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.UserPalateProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Vector>("BridgeVector")
                        .HasColumnType("vector(6)");

                    b.Property<Vector>("CentroidVector")
                        .HasColumnType("vector(8)");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("PreferenceVector")
                        .HasColumnType("vector(8)");

                    b.Property<int>("RatingsCount")
                        .HasColumnType("integer");

                    b.Property<float>("UserMean")
                        .HasColumnType("real");

                    b.HasKey("UserId", "Category");

                    b.ToTable("user_palate_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_palate_profiles_category", "\"Category\" IN ('beer','whiskey','wine')");

                            t.HasCheckConstraint("ck_user_palate_profiles_ratings_count", "\"RatingsCount\" >= 0");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HiddenBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Hours")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("MergedIntoVenueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Tier")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("VenueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MergedIntoVenueId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_venues_normalized_name_trgm")
                        .HasFilter("\"VenueType\" = 'venue'");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_venues_one_home_bar_per_user")
                        .HasFilter("\"VenueType\" = 'home_bar'");

                    b.ToTable("venues", null, t =>
                        {
                            t.HasCheckConstraint("ck_venues_geo_pairing", "(\"Latitude\" IS NULL) = (\"Longitude\" IS NULL)");

                            t.HasCheckConstraint("ck_venues_geo_range", "(\"Latitude\" IS NULL OR (\"Latitude\" >= -90 AND \"Latitude\" <= 90)) AND (\"Longitude\" IS NULL OR (\"Longitude\" >= -180 AND \"Longitude\" <= 180))");

                            t.HasCheckConstraint("ck_venues_hidden_pairing", "(\"HiddenAt\" IS NULL) = (\"HiddenBy\" IS NULL)");

                            t.HasCheckConstraint("ck_venues_home_bar_never_merged", "\"VenueType\" <> 'home_bar' OR \"Status\" = 'active'");

                            t.HasCheckConstraint("ck_venues_home_bar_no_geo", "\"VenueType\" <> 'home_bar' OR (\"Latitude\" IS NULL AND \"Address\" IS NULL)");

                            t.HasCheckConstraint("ck_venues_home_bar_private", "\"VenueType\" <> 'home_bar' OR (\"OwnerUserId\" IS NOT NULL AND \"Visibility\" = 'private')");

                            t.HasCheckConstraint("ck_venues_merge_pairing", "(\"Status\" = 'merged') = (\"MergedIntoVenueId\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_venues_no_self_merge", "\"MergedIntoVenueId\" IS NULL OR \"MergedIntoVenueId\" <> \"Id\"");

                            t.HasCheckConstraint("ck_venues_owner_visibility", "\"OwnerUserId\" IS NOT NULL OR \"Visibility\" = 'public'");

                            t.HasCheckConstraint("ck_venues_status", "\"Status\" IN ('active','merged')");

                            t.HasCheckConstraint("ck_venues_tier", "\"Tier\" IS NULL OR \"Tier\" IN ('wiki','verified')");

                            t.HasCheckConstraint("ck_venues_tier_pairing", "(\"VenueType\" = 'venue') = (\"Tier\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_venues_type", "\"VenueType\" IN ('home_bar','venue')");

                            t.HasCheckConstraint("ck_venues_visibility", "\"Visibility\" IN ('public','private')");
                        });
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.VenueMenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DrinkId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DrinkId");

                    b.HasIndex("VenueId", "DrinkId")
                        .IsUnique()
                        .HasDatabaseName("ux_venue_menu_items_venue_drink");

                    b.ToTable("venue_menu_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_venue_menu_items_owner_visibility", "\"CreatedByUserId\" IS NOT NULL OR \"Visibility\" = 'public'");

                            t.HasCheckConstraint("ck_venue_menu_items_price", "\"Price\" IS NULL OR \"Price\" >= 0");

                            t.HasCheckConstraint("ck_venue_menu_items_source", "\"Source\" IN ('crowd','venue')");

                            t.HasCheckConstraint("ck_venue_menu_items_visibility", "\"Visibility\" IN ('public','private')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.AnomalyFlag", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Checkin", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Drink", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarBrain.Api.Data.Entities.Producer", "Producer")
                        .WithMany("Drinks")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "MergedInto")
                        .WithMany()
                        .HasForeignKey("MergedIntoDrinkId", "Category")
                        .HasPrincipalKey("Id", "Category")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarBrain.Api.Data.Entities.Style", "Style")
                        .WithMany("Drinks")
                        .HasForeignKey("StyleId", "Category")
                        .HasPrincipalKey("Id", "Category")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("MergedInto");

                    b.Navigation("Producer");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.DrinkAttributeValue", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "Drink")
                        .WithMany("Attributes")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.MergeCandidate", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "SourceDrink")
                        .WithMany()
                        .HasForeignKey("SourceDrinkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarBrain.Api.Data.Entities.Producer", "SourceProducer")
                        .WithMany()
                        .HasForeignKey("SourceProducerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarBrain.Api.Data.Entities.Venue", "SourceVenue")
                        .WithMany()
                        .HasForeignKey("SourceVenueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "TargetDrink")
                        .WithMany()
                        .HasForeignKey("TargetDrinkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarBrain.Api.Data.Entities.Producer", "TargetProducer")
                        .WithMany()
                        .HasForeignKey("TargetProducerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarBrain.Api.Data.Entities.Venue", "TargetVenue")
                        .WithMany()
                        .HasForeignKey("TargetVenueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SourceDrink");

                    b.Navigation("SourceProducer");

                    b.Navigation("SourceVenue");

                    b.Navigation("TargetDrink");

                    b.Navigation("TargetProducer");

                    b.Navigation("TargetVenue");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Producer", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarBrain.Api.Data.Entities.Producer", "MergedInto")
                        .WithMany()
                        .HasForeignKey("MergedIntoProducerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("MergedInto");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Rating", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Drink");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Report", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarBrain.Api.Data.Entities.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarBrain.Api.Data.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Drink");

                    b.Navigation("Rating");

                    b.Navigation("Reporter");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Style", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.Style", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentStyleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.StyleAttributeValue", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Style", "Style")
                        .WithMany("Attributes")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.UserBadge", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.BadgeDefinition", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeSlug")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.UserCategoryInterest", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.UserMatchNeighbor", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "Neighbor")
                        .WithMany()
                        .HasForeignKey("NeighborUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Neighbor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.UserPalateProfile", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Venue", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarBrain.Api.Data.Entities.Venue", "MergedInto")
                        .WithMany()
                        .HasForeignKey("MergedIntoVenueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarBrain.Api.Data.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("MergedInto");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.VenueMenuItem", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarBrain.Api.Data.Entities.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarBrain.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Drink");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BarBrain.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Drink", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Producer", b =>
                {
                    b.Navigation("Drinks");
                });

            modelBuilder.Entity("BarBrain.Api.Data.Entities.Style", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Children");

                    b.Navigation("Drinks");
                });
#pragma warning restore 612, 618
        }
    }
}
